//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLife3D
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_accounts
    {
        public string PrincipalID { get; set; }
        public string ScopeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public short Created { get; set; }
        public short UserLevel { get; set; }
        public short UserFlags { get; set; }
        public string Name { get; set; }
    }
}
