//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLife3D
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_appearance
    {
        public string PrincipalID { get; set; }
        public string Appearance { get; set; }
    }
}
